export const ChessTab = {
  tabID: 5,
  eventID:5,
  track: 'Chess Swiss',
  title: 'Kasparovers',
  slug:'kasparovers',
  configuration:{    
    timeControl: '15+10', // 15 minutes + 10 seconds increment
    pairingMethod: 'Swiss', //other option is 'Eliminator'
  },
  schools:[
    {id:1, name:'Greenwood High'},
    {id:2, name:'Lakeside Academy'},
    {id:3, name:'Hilltop School'},
    {id:4, name:'Riverside Prep'},
    {id:5, name:'Maple Leaf School'},
    {id:6, name: 'Kings Academy'}
  ],
  participants: [
    { id: 1, name: 'Magnus Carlsen', school: 'Kings Academy' },
    { id: 2, name: 'Hikaru Nakamura', school: 'Lakeside Academy' },
    { id: 3, name: 'Fabiano Caruana', school: 'Hilltop School' },
    { id: 4, name: 'Alireza Firouzja', school: 'Riverside Prep' },
    { id: 5, name: 'Ding Liren', school: 'Maple Leaf School' },
    { id: 6, name: 'Anish Giri', school: 'Greenwood High' },
    { id: 7, name: 'Wesley So', school: 'Lakeside Academy' },
    { id: 8, name: 'Ian Nepomniachtchi', school: 'Hilltop School' },
    { id: 9, name: 'Levon Aronian', school: 'Riverside Prep' },
    { id: 10, name: 'Sergey Karjakin', school: 'Maple Leaf School' },
    { id: 11, name: 'Teimour Radjabov', school: 'Lakeside Academy' },
    { id: 12, name: 'Maxime Vachier-Lagrave', school: 'Maple Leaf School' },
    { id: 13, name: 'Shakh Mamedyarov', school: 'Riverside Prep' },
    { id: 14, name: 'Bobby Fischer', school: 'Riverside Prep' },
    { id: 15, name: 'Viswanathan Anand', school: 'Lakeside Academy'},
    { id: 16, name: 'Peter Svidler', school: 'Greenwood High' },
    { id: 17, name: 'Richard Rapport', school: 'Hilltop School' },
    { id: 18, name: 'Gata Kamsky', school: 'Maple Leaf School' },
    { id: 19, name: 'Vladimir Kramnik', school: 'Riverside Prep' },
    { id: 20, name: 'Pentala Harikrishna', school: 'Greenwood High' },
    { id: 21, name: 'Alexander Grischuk', school: 'Lakeside Academy' },
    { id: 22, name: 'Alexei Shirov', school: 'Hilltop School' },
    { id: 23, name: 'Leinier Dominguez', school: 'Maple Leaf School' },
    { id: 24, name: 'Veselin Topalov', school: 'Riverside Prep' },
    { id: 25, name: 'David Navara', school: 'Greenwood High' },
    { id: 26, name: 'Igor Kovalenko', school: 'Hilltop School' },
    { id: 27, name: 'Loek Van Wely', school: 'Lakeside Academy' },
    { id: 28, name: 'Rauf Mamedov', school: 'Maple Leaf School' },
    { id: 29, name: 'Evgeny Bareev', school: 'Riverside Prep' },
    { id: 30, name: 'Jan Timman', school: 'Greenwood High' },
    { id: 31, name: 'David Bronstein', school: 'Hilltop School' },
    { id: 32, name: 'Nigel Short', school: 'Lakeside Academy' },
  ],
  boards:[
    {id:1, name: 'board 1'},{id:2, name: 'board 2'},
    {id:3, name: 'board 3'},{id:4, name: 'board 4'},
    {id:5, name: 'board 5'},{id:6, name: 'board 6'},
    {id:7, name: 'board 7'},{id:8, name: 'board 8'},
    {id:9, name: 'board 9'},{id:10, name: 'board 10'},
    {id:11, name: 'board 11'},{id:12, name: 'board 12'},
    {id:13, name: 'board 13'},{id:14, name: 'board 14'},
    {id:15, name: 'board 15'},{id:16, name: 'board 16'},
    
  ],
  rounds: [
    {
      roundID: 1,
      pairings:[
        {boardID: 1, playerID:1, player2ID: 32},
        {boardID: 2, playerID:2, player2ID: 31},
        {boardID: 3, playerID:3, player2ID: 30},
        {boardID: 4, playerID:4, player2ID: 29},
        {boardID: 5, playerID:5, player2ID: 28},
        {boardID: 6, playerID:6, player2ID: 27},
        {boardID: 7, playerID:7, player2ID: 26},
        {boardID: 8, playerID:8, player2ID: 25},
        {boardID: 9, playerID:9, player2ID: 24},
        {boardID: 10, playerID:10, player2ID: 23},
        {boardID: 11, playerID:11, player2ID: 22},
        {boardID: 12, playerID:12, player2ID: 21},
        {boardID: 13, playerID:13, player2ID: 20},
        {boardID: 14, playerID:14, player2ID: 19},
        {boardID: 15, playerID:15, player2ID: 18},
        {boardID: 16, playerID:16, player2ID: 17},
      ],
      results:[
        {boardID: 1, result:[{playerID: 1, status: 'win'},{playerID: 32, status:'loss'}]},
        {boardID: 2, result:[{playerID: 2, status: 'draw'},{playerID: 31, status:'draw'}]},
        {boardID: 3, result:[{playerID: 3, status: 'win'},{playerID: 30, status:'loss'}]},
        {boardID: 4, result:[{playerID: 4, status: 'loss'},{playerID: 29, status:'win'}]},
        {boardID: 5, result:[{playerID: 5, status: 'win'},{playerID: 28, status:'loss'}]},
        {boardID: 6, result:[{playerID: 6, status: 'draw'},{playerID: 27, status:'draw'}]},
        {boardID: 7, result:[{playerID: 7, status: 'win'},{playerID: 26, status:'loss'}]},
        {boardID: 8, result:[{playerID: 8, status: 'loss'},{playerID: 25, status:'win'}]},
        {boardID: 9, result:[{playerID: 9, status: 'draw'},{playerID: 24, status:'draw'}]},
        {boardID: 10, result:[{playerID: 10, status: 'win'},{playerID: 23, status:'loss'}]},
        {boardID: 11, result:[{playerID: 11, status: 'win'},{playerID: 22, status:'loss'}]},
        {boardID: 12, result:[{playerID: 12, status: 'draw'},{playerID: 21, status:'draw'}]},
        {boardID: 13, result:[{playerID: 13, status: 'loss'},{playerID: 20, status:'win'}]},
        {boardID: 14, result:[{playerID: 14, status: 'win'},{playerID: 19, status:'loss'}]},
        {boardID: 15, result:[{playerID: 15, status: 'draw'},{playerID: 18, status:'draw'}]},
        {boardID: 16, result:[{playerID: 16, status: 'win'},{playerID: 17, status:'loss'}]},
      ]
    },
    {
      roundID: 2,
      pairings:[
        {boardID: 1, playerID:1, player2ID: 3},
        {boardID: 2, playerID:5, player2ID: 7},
        {boardID: 3, playerID:10, player2ID: 11},
        {boardID: 4, playerID:14, player2ID: 16},
        {boardID: 5, playerID:2, player2ID: 6},
        {boardID: 6, playerID:9, player2ID: 12},
        {boardID: 7, playerID:15, player2ID: 18},
        {boardID: 8, playerID:21, player2ID: 24},
        {boardID: 9, playerID:27, player2ID: 4},
        {boardID: 10, playerID:8, player2ID: 13},
        {boardID: 11, playerID:17, player2ID: 19},
        {boardID: 12, playerID:20, player2ID: 22},
        {boardID: 13, playerID:23, player2ID: 25},
        {boardID: 14, playerID:26, player2ID: 28},
        {boardID: 15, playerID:29, player2ID: 30},
        {boardID: 16, playerID:31, player2ID: 32},
      ],
      results:[
        {boardID: 1, result:[{playerID: 1, status: 'win'},{playerID: 3, status:'loss'}]},
        {boardID: 2, result:[{playerID: 5, status: 'draw'},{playerID: 7, status:'draw'}]},
        {boardID: 3, result:[{playerID: 10, status: 'loss'},{playerID: 11, status:'win'}]},
        {boardID: 4, result:[{playerID: 14, status: 'draw'},{playerID: 16, status:'draw'}]},
        {boardID: 5, result:[{playerID: 2, status: 'win'},{playerID: 6, status:'loss'}]},
        {boardID: 6, result:[{playerID: 9, status: 'draw'},{playerID: 12, status:'draw'}]},
        {boardID: 7, result:[{playerID: 15, status: 'loss'},{playerID: 18, status:'win'}]},
        {boardID: 8, result:[{playerID: 21, status: 'draw'},{playerID: 24, status:'draw'}]},
        {boardID: 9, result:[{playerID: 27, status: 'win'},{playerID: 4, status:'loss'}]},
        {boardID: 10, result:[{playerID: 8, status: 'win'},{playerID: 13, status:'loss'}]},
        {boardID: 11, result:[{playerID: 17, status: 'draw'},{playerID: 19, status:'draw'}]},
        {boardID: 12, result:[{playerID: 20, status: 'loss'},{playerID: 22, status:'win'}]},
        {boardID: 13, result:[{playerID: 23, status: 'win'},{playerID: 25, status:'loss'}]},
        {boardID: 14, result:[{playerID: 26, status: 'draw'},{playerID: 28, status:'draw'}]},
        {boardID: 15, result:[{playerID: 29, status: 'loss'},{playerID: 30, status:'win'}]},
        {boardID: 16, result:[{playerID: 31, status: 'win'},{playerID: 32, status:'loss'}]},
      ]
    },
    {
      roundID: 3,
      pairings:[
        {boardID: 1, playerID:1, player2ID: 11},
        {boardID: 2, playerID:2, player2ID: 27},
        {boardID: 3, playerID:5, player2ID: 7},
        {boardID: 4, playerID:14, player2ID: 16},
        {boardID: 5, playerID:8, player2ID: 22},
        {boardID: 6, playerID:18, player2ID: 31},
        {boardID: 7, playerID:9, player2ID: 12},
        {boardID: 8, playerID:15, player2ID: 21},
        {boardID: 9, playerID:24, player2ID: 17},
        {boardID: 10, playerID:19, player2ID: 30},
        {boardID: 11, playerID:23, player2ID: 10},
        {boardID: 12, playerID:3, player2ID: 6},
        {boardID: 13, playerID:4, player2ID: 13},
        {boardID: 14, playerID:20, player2ID: 25},
        {boardID: 15, playerID:26, player2ID: 28},
        {boardID: 16, playerID:29, player2ID: 32},
      ],
      results:[
        {boardID: 1, result:[{playerID: 1, status: 'draw'},{playerID: 11, status:'draw'}]},
        {boardID: 2, result:[{playerID: 2, status: 'win'},{playerID: 27, status:'loss'}]},
        {boardID: 3, result:[{playerID: 5, status: 'win'},{playerID: 7, status:'loss'}]},
        {boardID: 4, result:[{playerID: 14, status: 'win'},{playerID: 16, status:'loss'}]},
        {boardID: 5, result:[{playerID: 8, status: 'loss'},{playerID: 22, status:'win'}]},
        {boardID: 6, result:[{playerID: 18, status: 'draw'},{playerID: 31, status:'draw'}]},
        {boardID: 7, result:[{playerID: 9, status: 'draw'},{playerID: 12, status:'draw'}]},
        {boardID: 8, result:[{playerID: 15, status: 'loss'},{playerID: 21, status:'win'}]},
        {boardID: 9, result:[{playerID: 24, status: 'win'},{playerID: 17, status:'loss'}]},
        {boardID: 10, result:[{playerID: 19, status: 'draw'},{playerID: 30, status:'draw'}]},
        {boardID: 11, result:[{playerID: 23, status: 'loss'},{playerID: 10, status:'win'}]},
        {boardID: 12, result:[{playerID: 3, status: 'draw'},{playerID: 6, status:'draw'}]},
        {boardID: 13, result:[{playerID: 4, status: 'win'},{playerID: 13, status:'loss'}]},
        {boardID: 14, result:[{playerID: 20, status: 'loss'},{playerID: 25, status:'win'}]},
        {boardID: 15, result:[{playerID: 26, status: 'draw'},{playerID: 28, status:'draw'}]},
        {boardID: 16, result:[{playerID: 29, status: 'win'},{playerID: 32, status:'loss'}]},
      ]
    },
    {
      roundID: 4,
      pairings:[
        {boardID: 1, playerID:1, player2ID: 5},
        {boardID: 2, playerID:2, player2ID: 14},
        {boardID: 3, playerID:11, player2ID: 4},
        {boardID: 4, playerID:10, player2ID: 22},
        {boardID: 5, playerID:21, player2ID: 24},
        {boardID: 6, playerID:8, player2ID: 31},
        {boardID: 7, playerID:18, player2ID: 7},
        {boardID: 8, playerID:12, player2ID: 9},
        {boardID: 9, playerID:3, player2ID: 6},
        {boardID: 10, playerID:17, player2ID: 19},
        {boardID: 11, playerID:25, player2ID: 30},
        {boardID: 12, playerID:26, player2ID: 28},
        {boardID: 13, playerID:13, player2ID: 20},
        {boardID: 14, playerID:23, player2ID: 27},
        {boardID: 15, playerID:15, player2ID: 16},
        {boardID: 16, playerID:29, player2ID: 32},
      ],
      results:[
        {boardID: 1, result:[{playerID: 1, status: 'win'},{playerID: 5, status:'loss'}]},
        {boardID: 2, result:[{playerID: 2, status: 'win'},{playerID: 14, status:'loss'}]},
        {boardID: 3, result:[{playerID: 11, status: 'draw'},{playerID: 4, status:'draw'}]},
        {boardID: 4, result:[{playerID: 10, status: 'loss'},{playerID: 22, status:'win'}]},
        {boardID: 5, result:[{playerID: 21, status: 'draw'},{playerID: 24, status:'draw'}]},
        {boardID: 6, result:[{playerID: 8, status: 'win'},{playerID: 31, status:'loss'}]},
        {boardID: 7, result:[{playerID: 18, status: 'win'},{playerID: 7, status:'loss'}]},
        {boardID: 8, result:[{playerID: 12, status: 'loss'},{playerID: 9, status:'win'}]},
        {boardID: 9, result:[{playerID: 3, status: 'draw'},{playerID: 6, status:'draw'}]},
        {boardID: 10, result:[{playerID: 17, status: 'draw'},{playerID: 19, status:'draw'}]},
        {boardID: 11, result:[{playerID: 25, status: 'loss'},{playerID: 30, status:'win'}]},
        {boardID: 12, result:[{playerID: 26, status: 'draw'},{playerID: 28, status:'draw'}]},
        {boardID: 13, result:[{playerID: 13, status: 'loss'},{playerID: 20, status:'win'}]},
        {boardID: 14, result:[{playerID: 23, status: 'win'},{playerID: 27, status:'loss'}]},
        {boardID: 15, result:[{playerID: 15, status: 'loss'},{playerID: 16, status:'win'}]},
        {boardID: 16, result:[{playerID: 29, status: 'draw'},{playerID: 32, status:'draw'}]},
      ]
    },
    {
      roundID: 5,
      pairings:[
        {boardID: 1, playerID:1, player2ID: 2},
        {boardID: 2, playerID:5, player2ID: 11},
        {boardID: 3, playerID:22, player2ID: 8},
        {boardID: 4, playerID:18, player2ID: 4},
        {boardID: 5, playerID:30, player2ID: 23},
        {boardID: 6, playerID:14, player2ID: 20},
        {boardID: 7, playerID:9, player2ID: 3},
        {boardID: 8, playerID:6, player2ID: 12},
        {boardID: 9, playerID:21, player2ID: 24},
        {boardID: 10, playerID:26, player2ID: 28},
        {boardID: 11, playerID:17, player2ID: 19},
        {boardID: 12, playerID:31, player2ID: 32},
        {boardID: 13, playerID:7, player2ID: 10},
        {boardID: 14, playerID:15, player2ID: 16},
        {boardID: 15, playerID:25, player2ID: 27},
        {boardID: 16, playerID:13, player2ID: 29},
      ],
      results:[
        {boardID: 1, result:[{playerID: 1, status: 'draw'},{playerID: 2, status:'draw'}]},
        {boardID: 2, result:[{playerID: 5, status: 'win'},{playerID: 11, status:'loss'}]},
        {boardID: 3, result:[{playerID: 22, status: 'draw'},{playerID: 8, status:'draw'}]},
        {boardID: 4, result:[{playerID: 18, status: 'loss'},{playerID: 4, status:'win'}]},
        {boardID: 5, result:[{playerID: 30, status: 'win'},{playerID: 23, status:'loss'}]},
        {boardID: 6, result:[{playerID: 14, status: 'win'},{playerID: 20, status:'loss'}]},
        {boardID: 7, result:[{playerID: 9, status: 'draw'},{playerID: 3, status:'draw'}]},
        {boardID: 8, result:[{playerID: 6, status: 'loss'},{playerID: 12, status:'win'}]},
        {boardID: 9, result:[{playerID: 21, status: 'draw'},{playerID: 24, status:'draw'}]},
        {boardID: 10, result:[{playerID: 26, status: 'draw'},{playerID: 28, status:'draw'}]},
        {boardID: 11, result:[{playerID: 17, status: 'draw'},{playerID: 19, status:'draw'}]},
        {boardID: 12, result:[{playerID: 31, status: 'win'},{playerID: 32, status:'loss'}]},
        {boardID: 13, result:[{playerID: 7, status: 'loss'},{playerID: 10, status:'win'}]},
        {boardID: 14, result:[{playerID: 15, status: 'draw'},{playerID: 16, status:'draw'}]},
        {boardID: 15, result:[{playerID: 25, status: 'loss'},{playerID: 27, status:'win'}]},
        {boardID: 16, result:[{playerID: 13, status: 'win'},{playerID: 29, status:'loss'}]},
      ]
    },
  ],
  standings: [
    { rank: 1, playerID: 1, name: 'Magnus Carlsen', school: 'Kings Academy', score: 4, wins: 3, draws: 2, losses: 0 },
    { rank: 2, playerID: 2, name: 'Hikaru Nakamura', school: 'Lakeside Academy', score: 4, wins: 3, draws: 2, losses: 0 },
    { rank: 3, playerID: 5, name: 'Ding Liren', school: 'Maple Leaf School', score: 3.5, wins: 3, draws: 1, losses: 1 },
    { rank: 4, playerID: 11, name: 'Teimour Radjabov', school: 'Lakeside Academy', score: 3.5, wins: 3, draws: 1, losses: 1 },
    { rank: 5, playerID: 14, name: 'Bobby Fischer', school: 'Riverside Prep', score: 3.5, wins: 3, draws: 1, losses: 1 },
    { rank: 6, playerID: 18, name: 'Gata Kamsky', school: 'Maple Leaf School', score: 3, wins: 2, draws: 2, losses: 1 },
    { rank: 7, playerID: 30, name: 'Jan Timman', school: 'Greenwood High', score: 3, wins: 3, draws: 0, losses: 2 },
    { rank: 8, playerID: 3, name: 'Fabiano Caruana', school: 'Hilltop School', score: 2.5, wins: 1, draws: 3, losses: 1 },
    { rank: 9, playerID: 12, name: 'Maxime Vachier-Lagrave', school: 'Maple Leaf School', score: 2.5, wins: 1, draws: 3, losses: 1 },
    { rank: 10, playerID: 16, name: 'Peter Svidler', school: 'Greenwood High', score: 2.5, wins: 2, draws: 1, losses: 2 },
    { rank: 11, playerID: 24, name: 'Veselin Topalov', school: 'Riverside Prep', score: 2.5, wins: 1, draws: 3, losses: 1 },
    { rank: 12, playerID: 29, name: 'Evgeny Bareev', school: 'Riverside Prep', score: 2.5, wins: 2, draws: 1, losses: 2 },
    { rank: 13, playerID: 31, name: 'David Bronstein', school: 'Hilltop School', score: 2.5, wins: 2, draws: 1, losses: 2 },
    { rank: 14, playerID: 8, name: 'Ian Nepomniachtchi', school: 'Hilltop School', score: 2, wins: 2, draws: 1, losses: 2 },
    { rank: 15, playerID: 22, name: 'Alexei Shirov', school: 'Hilltop School', score: 2, wins: 2, draws: 0, losses: 3 },
    { rank: 16, playerID: 27, name: 'Loek Van Wely', school: 'Lakeside Academy', score: 2, wins: 2, draws: 0, losses: 3 },
    { rank: 17, playerID: 4, name: 'Alireza Firouzja', school: 'Riverside Prep', score: 1.5, wins: 1, draws: 1, losses: 3 },
    { rank: 18, playerID: 6, name: 'Anish Giri', school: 'Greenwood High', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 19, playerID: 7, name: 'Wesley So', school: 'Lakeside Academy', score: 1.5, wins: 1, draws: 1, losses: 3 },
    { rank: 20, playerID: 9, name: 'Levon Aronian', school: 'Riverside Prep', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 21, playerID: 10, name: 'Sergey Karjakin', school: 'Maple Leaf School', score: 1.5, wins: 2, draws: 0, losses: 3 },
    { rank: 22, playerID: 17, name: 'Richard Rapport', school: 'Hilltop School', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 23, playerID: 19, name: 'Vladimir Kramnik', school: 'Riverside Prep', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 24, playerID: 21, name: 'Alexander Grischuk', school: 'Lakeside Academy', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 25, playerID: 26, name: 'Igor Kovalenko', school: 'Hilltop School', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 26, playerID: 28, name: 'Rauf Mamedov', school: 'Maple Leaf School', score: 1.5, wins: 0, draws: 3, losses: 2 },
    { rank: 27, playerID: 13, name: 'Shakh Mamedyarov', school: 'Riverside Prep', score: 1, wins: 1, draws: 0, losses: 4 },
    { rank: 28, playerID: 15, name: 'Viswanathan Anand', school: 'Lakeside Academy', score: 1, wins: 0, draws: 2, losses: 3 },
    { rank: 29, playerID: 20, name: 'Pentala Harikrishna', school: 'Greenwood High', score: 1, wins: 1, draws: 0, losses: 4 },
    { rank: 30, playerID: 25, name: 'David Navara', school: 'Greenwood High', score: 1, wins: 1, draws: 0, losses: 4 },
    { rank: 31, playerID: 23, name: 'Leinier Dominguez', school: 'Maple Leaf School', score: 0, wins: 0, draws: 0, losses: 5 },
    { rank: 32, playerID: 32, name: 'Nigel Short', school: 'Lakeside Academy', score: 0.5, wins: 0, draws: 1, losses: 4 },
  ],
};
