export const ChessTab = {
  tabID: 3,
  track: 'Chess',
  title: 'Chess Open',
  timeControl: '15+10', // 15 minutes + 10 seconds increment
  pairingMethod: 'Swiss',
  schools:[
    {id:1, name:'Greenwood High'},
    {id:2, name:'Lakeside Academy'},
    {id:3, name:'Hilltop School'},
    {id:4, name:'Riverside Prep'},
    {id:5, name:'Maple Leaf School'},
    {id:6, name: 'Kings Academy'}
  ],
  participants: [
    { id: 1, name: 'Magnus Carlsen', school: 'Kings Academy' },
    { id: 2, name: 'Hikaru Nakamura', school: 'Lakeside Academy' },
    { id: 3, name: 'Fabiano Caruana', school: 'Hilltop School' },
    { id: 4, name: 'Alireza Firouzja', school: 'Riverside Prep' },
    { id: 5, name: 'Ding Liren', school: 'Maple Leaf School' },
    { id: 6, name: 'Anish Giri', school: 'Greenwood High' },
    { id: 7, name: 'Wesley So', school: 'Lakeside Academy' },
    { id: 8, name: 'Ian Nepomniachtchi', school: 'Hilltop School' },
    { id: 9, name: 'Levon Aronian', school: 'Riverside Prep' },
    { id: 10, name: 'Sergey Karjakin', school: 'Maple Leaf School' },
    { id: 11, name: 'Teimour Radjabov', school: 'Lakeside Academy' },
    { id: 12, name: 'Maxime Vachier-Lagrave', school: 'Maple Leaf School' },
    { id: 13, name: 'Shakh Mamedyarov', school: 'Riverside Prep' },
    { id: 14, name: 'Bobby Fischer', school: 'Riverside Prep' },
    { id: 15, name: 'Viswanathan Anand', school: 'Lakeside Academy'},
    { id: 16, name: 'Peter Svidler', school: 'Greenwood High' },
    { id: 17, name: 'Richard Rapport', school: 'Hilltop School' },
    { id: 18, name: 'Gata Kamsky', school: 'Maple Leaf School' },
    { id: 19, name: 'Vladimir Kramnik', school: 'Riverside Prep' },
    { id: 20, name: 'Pentala Harikrishna', school: 'Greenwood High' },
    { id: 21, name: 'Alexander Grischuk', school: 'Lakeside Academy' },
    { id: 22, name: 'Alexei Shirov', school: 'Hilltop School' },
    { id: 23, name: 'Leinier Dominguez', school: 'Maple Leaf School' },
    { id: 24, name: 'Veselin Topalov', school: 'Riverside Prep' },
    { id: 25, name: 'David Navara', school: 'Greenwood High' },
    { id: 26, name: 'Igor Kovalenko', school: 'Hilltop School' },
    { id: 27, name: 'Loek Van Wely', school: 'Lakeside Academy' },
    { id: 28, name: 'Rauf Mamedov', school: 'Maple Leaf School' },
    { id: 29, name: 'Evgeny Bareev', school: 'Riverside Prep' },
    { id: 30, name: 'Jan Timman', school: 'Greenwood High' },
    { id: 31, name: 'David Bronstein', school: 'Hilltop School' },
    { id: 32, name: 'Nigel Short', school: 'Lakeside Academy' },
  ],
  rounds: [
    {
      roundID: 1,
      
    },
  ],
};
