export const PStab={
  tabID:2,
  track:'Public Speaking',
  title:'Public Speaking Seniors',
  schools:[
    {id:1, name:'Greenwood High'},
    {id:2, name:'Lakeside Academy'},
    {id:3, name:'Hilltop School'},
    {id:4, name:'Riverside Prep'},
    {id:5, name:'Maple Leaf School'},
  ],
  participants:[
    {id:1, name:'Alice Johnson', school:'Greenwood High'},
    {id:2, name:'Bob Martinez', school:'Lakeside Academy'},
    {id:3, name:'Charlie Smith', school:'Hilltop School'},
    {id:4, name:'Diana Chen', school:'Riverside Prep'},
    {id:5, name:'Ethan Williams', school:'Maple Leaf School'},
    {id:6, name:'Fiona Brown', school:'Greenwood High'},
    {id:7, name:'George Davis', school:'Lakeside Academy'},
    {id:8, name:'Hannah Wilson', school:'Hilltop School'},
    {id:9, name:'Ian Anderson', school:'Riverside Prep'},
    {id:10, name:'Julia Taylor', school:'Maple Leaf School'},
    {id:11, name:'Kevin Miller', school:'Lakeside Academy'},
    {id:12, name:'Laura Jackson', school:'Maple Leaf School'},
    {id:13, name:'Michael White', school:'Riverside Prep'},
    {id:14, name:'Nina Harris', school:'Riverside Prep'},
    {id:15, name:'Oscar Martin', school:'Lakeside Academy'},
    {id:16, name:'Paula Thompson', school:'Greenwood High'},
    {id:17, name:'Quentin Garcia', school:'Hilltop School'},
    {id:18, name:'Rachel Lee', school:'Riverside Prep'},
    {id:19, name:'Sam Rodriguez', school:'Maple Leaf School'},
    {id:20, name:'Tina Clark', school:'Greenwood High'},
    {id:21, name:'Uma Patel', school:'Hilltop School'},
    {id:22, name:'Victor Lopez', school:'Lakeside Academy'},
    {id:23, name:'Wendy Turner', school:'Maple Leaf School'},
    {id:24, name:'Xavier Phillips', school:'Riverside Prep'},
    {id:25, name:'Yvonne Campbell', school:'Greenwood High'},
    {id:26, name:'Zach Parker', school:'Hilltop School'},
    {id:27, name:'Aaron Edwards', school:'Lakeside Academy'},
    {id:28, name:'Bella Collins', school:'Maple Leaf School'},
    {id:29, name:'Caleb Reeves', school:'Riverside Prep'},
    {id:30, name:'Daisy Morris', school:'Greenwood High'},
  ],
  judges:[
    {id:1, name:'Clare Kennedy'},
    {id:2, name:'Bella Sullivan'},
    {id:3, name:'Bosibori Ochieng'},
    {id:4, name:'Boaz Adler'},
    {id:5, name:'Obadiah Wright'},
    {id:6, name:'Hannah Freeman'},
    {id:7, name:'Abigail Stone'},
    {id:8, name:'David Mitchell'},
    {id:11, name:'Eli Benjamin'},
    {id:12, name:'Loyd Harrison'},
  ],
  rooms:[
    {id:1, name:'Public Speaking Room 1'},
    {id:2, name:'Public Speaking Room 2'},
    {id:3, name:'Public Speaking Room 3'},
    {id:4, name:'Public Speaking Room 4'},
    {id:5, name:'Public Speaking Room 5'},
  ],
  speeches:[
    {id:1, type:'Selling', timeLimit:'4 minutes', prompt:'More than just a toy'},
    {id:2, type:'Creative', timeLimit:'4 minutes', prompt:'Tweet from the past'},
    {id:3, type:'Dillemma', timeLimit:'4 minutes', prompt:'The world or I'},
    {id:4, type:'Impromptu', timeLimit:'2 minutes', prompt:'The future of work'},
    {id:5, type:'Philosophical', timeLimit:'4 minutes', prompt:'Votes for naught'},
    {id:6, type:'Special Occasion', timeLimit:'5 minutes', prompt:'Like None Other'}
  ],
  configuration:{
    speechOrder:'random',
    judgeAssignment:'random',
    roomAssignment:'random',
    lowerPointLimit: 30,
    upperPointLimit: 90
  },
  rounds:[
    {roundID:1, name:'Round 1', speechID:1, level:'Preliminary',
      rooms:[
        {roomID:1, judges:[{judgeID:1, role: 'Chair'},{judgeID:2, role:'Panelist'}], participantIDs:[1,2,3,4,5,6],
          result:[
            {participantID:1, score:85},
            {participantID:2, score:78},
            {participantID:3, score:42},
            {participantID:4, score:78},
            {participantID:5, score:80},
            {participantID:6, score:82},
          ],
        },
        {roomID:2, judges:[{judgeID:3, role: 'Chair'},{judgeID:4, role:'Panelist'}], participantIDs:[7,8,9,10,11,12],
          result:[
            {participantID:7, score:79},
            {participantID:8, score:84},
            {participantID:9, score:77},
            {participantID:10, score:50},
            {participantID:11, score:71},
            {participantID:12, score:86},
          ],
      },
        {roomID:3, judges:[{judgeID:5, role: 'Chair'},{judgeID:6, role:'Panelist'}], participantIDs:[13,14,15,16,17,18],
          result:[
            {participantID:13, score:88},
            {participantID:14, score:82},
            {participantID:15, score:79},
            {participantID:16, score:81},
            {participantID:17, score:75},
            {participantID:18, score:80},
          ],
        },
        {roomID:4, judges:[{judgeID:7, role: 'Chair'},{judgeID:8, role:'Panelist'}], participantIDs:[19,20,21,22,23,24],
          result:[
            {participantID:19, score:77},
            {participantID:20, score:85},
            {participantID:21, score:80},
            {participantID:22, score:78},
            {participantID:23, score:82},
            {participantID:24, score:79},
          ],
        },
        {roomID:5, judges:[{judgeID:9, role: 'Chair'},{judgeID:10, role:'Panelist'}], participantIDs:[25,26,27,28,29,30],
          result:[
            {participantID:25, score:83},
            {participantID:26, score:80},
            {participantID:27, score:78},
            {participantID:28, score:85},
            {participantID:29, score:81},
            {participantID:30, score:77},
          ],
        },
      ],
    },
    {roundID:2, name:'Round 2', speechID:2, level:'Preliminary',
      rooms:[
        {roomID:1, judges:[{judgeID:1, role: 'Chair'},{judgeID:2, role:'Panelist'}], participantIDs:[1,7,13,19,25,5],
          result:[
            {participantID:1, score:88},
            {participantID:7, score:82},
            {participantID:13, score:90},
            {participantID:19, score:80},
            {participantID:25, score:85},
            {participantID:5, score:64},
          ],
        },
        {roomID:2, judges:[{judgeID:3, role: 'Chair'},{judgeID:4, role:'Panelist'}], participantIDs:[2,8,14,20,26,6],
          result:[
            {participantID:2, score:75},
            {participantID:8, score:81},
            {participantID:14, score:78},
            {participantID:20, score:86},
            {participantID:26, score:72},
            {participantID:6, score:79},
          ],
        },
        {roomID:3, judges:[{judgeID:5, role: 'Chair'},{judgeID:6, role:'Panelist'}], participantIDs:[3,9,15,21,27,11],
          result:[
            {participantID:3, score:82},
            {participantID:9, score:77},
            {participantID:15, score:84},
            {participantID:21, score:80},
            {participantID:27, score:76},
            {participantID:11, score:73},
          ],
        },
        {roomID:4, judges:[{judgeID:7, role: 'Chair'},{judgeID:8, role:'Panelist'}], participantIDs:[4,10,16,22,28,12],
          result:[
            {participantID:4, score:79},
            {participantID:10, score:85},
            {participantID:16, score:81},
            {participantID:22, score:78},
            {participantID:28, score:82},
            {participantID:12, score:80},
          ],
        },
        {roomID:5, judges:[{judgeID:9, role: 'Chair'},{judgeID:10, role:'Panelist'}], participantIDs:[5,11,17,23,29,13],
          result:[
            {participantID:5, score:70},
            {participantID:11, score:74},
            {participantID:17, score:83},
            {participantID:23, score:79},
            {participantID:29, score:77},
            {participantID:13, score:86},
          ],
        },
      ],
    },
    { roundID:3, name: 'Round 3', speechID:3, level:'Preliminary',
      rooms:[
        {roomID:1, judges:[{judgeID:2, role: 'Chair'},{judgeID:3, role:'Panelist'}], participantIDs:[1,8,15,22,29,6],
          result:[
            {participantID:1, score:90},
            {participantID:8, score:83},
            {participantID:15, score:78},
            {participantID:22, score:81},
            {participantID:29, score:79},
            {participantID:6, score:85},
          ],
        },
        {roomID:2, judges:[{judgeID:4, role: 'Chair'},{judgeID:5, role:'Panelist'}], participantIDs:[2,9,16,23,30,7],
          result:[
            {participantID:2, score:80},
            {participantID:9, score:76},
            {participantID:16, score:82},
            {participantID:23, score:84},
            {participantID:30, score:78},
            {participantID:7, score:77},
          ],
        },
        {roomID:3, judges:[{judgeID:6, role: 'Chair'},{judgeID:7, role:'Panelist'}], participantIDs:[3,10,17,24,1,8],
          result:[
            {participantID:3, score:85},
            {participantID:10, score:88},
            {participantID:17, score:79},
            {participantID:24, score:82},
            {participantID:1, score:87},
            {participantID:8, score:80},
          ],
        },
        {roomID:4, judges:[{judgeID:8, role: 'Chair'},{judgeID:9, role:'Panelist'}], participantIDs:[4,11,18,25,2,9],
          result:[
            {participantID:4, score:78},
            {participantID:11, score:81},
            {participantID:18, score:86},
            {participantID:25, score:83},
            {participantID:2, score:75},
            {participantID:9, score:79},
          ],
        },
        {roomID:5, judges:[{judgeID:10, role: 'Chair'},{judgeID:1, role:'Panelist'}], participantIDs:[5,12,19,26,3,10],
          result:[
            {participantID:5, score:76},
            {participantID:12, score:84},
            {participantID:19, score:88},
            {participantID:26, score:80},
            {participantID:3, score:81},
            {participantID:10, score:82},
          ],
        },
      ]
    },
    { roundID:4, name: 'Round 4', speechID:4, level:'Preliminary',
      rooms:[
        {roomID:1, judges:[{judgeID:3, role: 'Chair'},{judgeID:5, role:'Panelist'}], participantIDs:[1,9,17,25,2,10],
          result:[
            {participantID:1, score:88},
            {participantID:9, score:85},
            {participantID:17, score:80},
            {participantID:25, score:86},
            {participantID:2, score:79},
            {participantID:10, score:83},
          ],
        },
        {roomID:2, judges:[{judgeID:4, role: 'Chair'},{judgeID:6, role:'Panelist'}], participantIDs:[3,11,19,27,4,12],
          result:[
            {participantID:3, score:84},
            {participantID:11, score:78},
            {participantID:19, score:90},
            {participantID:27, score:75},
            {participantID:4, score:82},
            {participantID:12, score:81},
          ],
        },
        {roomID:3, judges:[{judgeID:7, role: 'Chair'},{judgeID:8, role:'Panelist'}], participantIDs:[5,13,21,29,6,14],
          result:[
            {participantID:5, score:77},
            {participantID:13, score:89},
            {participantID:21, score:83},
            {participantID:29, score:80},
            {participantID:6, score:86},
            {participantID:14, score:78},
          ],
        },
        {roomID:4, judges:[{judgeID:9, role: 'Chair'},{judgeID:10, role:'Panelist'}], participantIDs:[7,15,23,30,8,16],
          result:[
            {participantID:7, score:81},
            {participantID:15, score:85},
            {participantID:23, score:82},
            {participantID:30, score:79},
            {participantID:8, score:87},
            {participantID:16, score:76},
          ],
        },
        {roomID:5, judges:[{judgeID:1, role: 'Chair'},{judgeID:2, role:'Panelist'}], participantIDs:[18,20,24,26,28,27],
          result:[
            {participantID:18, score:88},
            {participantID:20, score:83},
            {participantID:24, score:79},
            {participantID:26, score:81},
            {participantID:28, score:82},
            {participantID:27, score:80},
          ],
        },
      ]
    },
    { roundID:5, name: 'Semi Finals', speechID:5,level:'Breaks',
      rooms:[
        {roomID:1, judges:[{judgeID:1, role:'Chair'},{judgeID:2, role:'Panelist'},{judgeID:3, role:'Panelist'}], participantIDs:[1,3,5,7,9,11],
          result:[
            {participantID:1, score:89},
            {participantID:3, score:86},
            {participantID:5, score:84},
            {participantID:7, score:82},
            {participantID:9, score:80},
            {participantID:11, score:78},
          ]
        },
        {roomID:2, judges:[{judgeID:4, role:'Chair'},{judgeID:5, role:'Panelist'},{judgeID:6, role:'Panelist'}], participantIDs:[13,15,17,19,21,23],
          result:[
            {participantID:13, score:88},
            {participantID:15, score:87},
            {participantID:17, score:85},
            {participantID:19, score:83},
            {participantID:21, score:81},
            {participantID:23, score:79},
          ]
        }
      ]
    },
    { roundID:6, name: 'Finals', speechID:6, level:'Breaks',
      rooms:[
        {roomID:1, judges:[{judgeID:7, role:'Chair'},{judgeID:8, role:'Panelist'},{judgeID:9, role:'Panelist'}], participantIDs:[1,13,3,15,5,17],
          result:[
            {participantID:1, score:91},
            {participantID:13, score:89},
            {participantID:3, score:87},
            {participantID:15, score:86},
            {participantID:5, score:85},
            {participantID:17, score:84},
          ]
        }
      ]
    }
  ],

};