export const WSDCData = {
  title: 'Kivumbi Opens',
  slug:'kivumbi-opens',
  tabID: 2,
  eventID:5,
  track: 'WSDC',
  configuration: {
    prelimRounds: 3,
    eliminationRounds: ['Semifinal','Final'],
    teamSize: 3,
  },
  teams: [
    { teamID: 1, name: 'Greenwood A', school: 'Greenwood High', members: ['Alice Johnson','Ben Carter','Cara Lee'] },
    { teamID: 2, name: 'Lakeside A', school: 'Lakeside Academy', members: ['Bob Martinez','Cody Nguyen','Dana Ruiz'] },
    { teamID: 3, name: 'Hilltop A', school: 'Hilltop School', members: ['Charlie Smith','Evan Park','Fiona Brown'] },
    { teamID: 4, name: 'Riverside A', school: 'Riverside Prep', members: ['Diana Chen','George Young','Hannah Wilson'] },
    { teamID: 5, name: 'Maple A', school: 'Maple Leaf School', members: ['Ethan Williams','Ivy Zhao','James Osei'] },
    { teamID: 6, name: 'Greenwood B', school: 'Greenwood High', members: ['Kara Bell','Liam Fox','Maya Patel'] },
    { teamID: 7, name: 'Lakeside B', school: 'Lakeside Academy', members: ['Noah Kim','Olivia Hart','Paul Santos'] },
    { teamID: 8, name: 'Hilltop B', school: 'Hilltop School', members: ['Quinn Blake','Rosa Park','Samir Khan'] },
    { teamID: 9, name: 'Riverside B', school: 'Riverside Prep', members: ['Tina Clark','Uma Patel','Vikram Rao'] },
    { teamID: 10, name: 'Maple B', school: 'Maple Leaf School', members: ['Wendy Turner','Xavier Phillips','Yvonne Campbell'] },
    { teamID: 11, name: 'Greenwood C', school: 'Greenwood High', members: ['Zach Parker','Aaron Brooks','Bella Collins'] },
    { teamID: 12, name: 'Lakeside C', school: 'Lakeside Academy', members: ['Caleb Reeves','Daisy Morris','Eli Benjamin'] },
    { teamID: 13, name: 'Hilltop C', school: 'Hilltop School', members: ['Faisal Ahmed','Gina Torres','Hector Ramos'] },
    { teamID: 14, name: 'Riverside C', school: 'Riverside Prep', members: ['Ibrahim Diallo','Jade Lin','Kofi Mensah'] },
    { teamID: 15, name: 'Maple C', school: 'Maple Leaf School', members: ['Lana Cho','Mason Reid','Nora Wells'] },
    { teamID: 16, name: 'Greenwood D', school: 'Greenwood High', members: ['Owen Price','Pia Romano','Quentin Garcia'] },
    { teamID: 17, name: 'Lakeside D', school: 'Lakeside Academy', members: ['Riley Fox','Sana Iqbal','Tariq Malik'] },
    { teamID: 18, name: 'Hilltop D', school: 'Hilltop School', members: ['Umar Khan','Vera Li','Will Grant'] },
    { teamID: 19, name: 'Riverside D', school: 'Riverside Prep', members: ['Ximena Cruz','Yusuf Ibrahim','Zara Khan'] },
    { teamID: 20, name: 'Maple D', school: 'Maple Leaf School', members: ['Amir Rahman','Bea Santos','Carl Jensen'] },
    { teamID: 21, name: 'Greenwood E', school: 'Greenwood High', members: ['Dana Vega','Evan Ross','Felicity Day'] },
    { teamID: 22, name: 'Lakeside E', school: 'Lakeside Academy', members: ['Galen Price','Hana Mori','Ian Stone'] },
    { teamID: 23, name: 'Hilltop E', school: 'Hilltop School', members: ['Jamal Brown','Kira Novak','Leo Park'] },
    { teamID: 24, name: 'Riverside E', school: 'Riverside Prep', members: ['Mira Singh','Nikhil Rao','Oona Byrne'] },
    { teamID: 25, name: 'Maple E', school: 'Maple Leaf School', members: ['Parker Holt','Queenie Ma','Rafa Silva'] },
    { teamID: 26, name: 'Greenwood F', school: 'Greenwood High', members: ['Sofia Diaz','Theo Wright','Una Bell'] },
    { teamID: 27, name: 'Lakeside F', school: 'Lakeside Academy', members: ['Vance Cole','Willa Stone','Xander Holt'] },
    { teamID: 28, name: 'Hilltop F', school: 'Hilltop School', members: ['Yara Ahmed','Zane Lowe','Asha Nair'] },
    { teamID: 29, name: 'Riverside F', school: 'Riverside Prep', members: ['Brett Lang','Celia Ford','Damon Yu'] },
    { teamID: 30, name: 'Maple F', school: 'Maple Leaf School', members: ['Elena Park','Finn O"Brien','Gordon Ma'] },
    { teamID: 31, name: 'Greenwood G', school: 'Greenwood High', members: ['Holly West','Imran Syed','Juno Kaur'] },
    { teamID: 32, name: 'Lakeside G', school: 'Lakeside Academy', members: ['Kaden Ross','Lara Bell','Mira Holt'] },
    { teamID: 33, name: 'Hilltop G', school: 'Hilltop School', members: ['Nate Long','Orla Finch','Peyton Cruz'] },
    { teamID: 34, name: 'Riverside G', school: 'Riverside Prep', members: ['Quincy Shaw','Rhea Kapoor','Sven Olsen'] },
    { teamID: 35, name: 'Maple G', school: 'Maple Leaf School', members: ['Tess Morgan','Umar Farooq','Violet King'] },
    { teamID: 36, name: 'Greenwood H', school: 'Greenwood High', members: ['Wen Zhou','Xia Lin','Yara Mendes'] },
    { teamID: 37, name: 'Lakeside H', school: 'Lakeside Academy', members: ['Zion Park','Aaliyah Khan','Benito Ruiz'] },
    { teamID: 38, name: 'Hilltop H', school: 'Hilltop School', members: ['Carmen Lee','Dexter Shaw','Elio Romano'] },
    { teamID: 39, name: 'Swing Team 1', school: 'Swing', swing: true, members: ['Swing A','Swing B','Swing C'] },
    { teamID: 40, name: 'Swing Team 2', school: 'Swing', swing: true, members: ['Swing D','Swing E','Swing F'] },
  ],
  
  schools: [
    'Greenwood High',
    'Lakeside Academy',
    'Hilltop School',
    'Riverside Prep',
    'Maple Leaf School',
    'Kings Academy',
    'Swing'
  ],

  participants: [
    // flattened list of individuals (3 per team). participantID increments.
    { participantID: 1, name: 'Alice Johnson', teamID: 1 },
    { participantID: 2, name: 'Ben Carter', teamID: 1 },
    { participantID: 3, name: 'Cara Lee', teamID: 1 },
    { participantID: 4, name: 'Bob Martinez', teamID: 2 },
    { participantID: 5, name: 'Cody Nguyen', teamID: 2 },
    { participantID: 6, name: 'Dana Ruiz', teamID: 2 },
    { participantID: 7, name: 'Charlie Smith', teamID: 3 },
    { participantID: 8, name: 'Evan Park', teamID: 3 },
    { participantID: 9, name: 'Fiona Brown', teamID: 3 },
    { participantID: 10, name: 'Diana Chen', teamID: 4 },
    { participantID: 11, name: 'George Young', teamID: 4 },
    { participantID: 12, name: 'Hannah Wilson', teamID: 4 },
    // ... remaining participants omitted for brevity
  ],
  adjudicators: [
    { adjID: 1, name: 'Alice Reed' },
    { adjID: 2, name: 'Bob Carter' },
    { adjID: 3, name: 'Clare Zhou' },
    { adjID: 4, name: 'Danielle Park' },
    { adjID: 5, name: 'Ethan Liu' },
    { adjID: 6, name: 'Farah Ahmed' },
    { adjID: 7, name: 'Greg Novak' },
    { adjID: 8, name: 'Hannah O"Neill' },
    { adjID: 9, name: 'Ivan Smirnov' },
    { adjID: 10, name: 'Jasmin Roy' },
  ],
  rooms: Array.from({ length: 20 }, (_, i) => ({ roomID: i + 1, name: `Chamber ${i + 1}` })),

  rounds: [
    // Prelim Round 1 - 20 debates (40 teams)
    {
      roundID: 1,
      name: 'Prelim 1',
      pairings: [
        // pair team 1..40 as (1 vs 40), (2 vs 39), ...
        ...Array.from({ length: 20 }, (_, i) => ({
          roomID: i + 1,
          govTeamID: i + 1,
          oppTeamID: 40 - i,
          adjudicators: [((i % 10) + 1)],
        })),
      ],
      results: [
        // realistic mixed results; top teams (1-6) win, swings lose some
        // We'll list results in same order as pairings
        ...[
          { winnerTeamID: 1, govScore: 79, oppScore: 72, speakerPoints: { gov: [27,26,26], opp: [24,24,24] } },
          { winnerTeamID: 2, govScore: 76, oppScore: 74, speakerPoints: { gov: [25,26,25], opp: [24,25,25] } },
          { winnerTeamID: 3, govScore: 80, oppScore: 70, speakerPoints: { gov: [27,27,26], opp: [23,23,24] } },
          { winnerTeamID: 29, govScore: 74, oppScore: 73, speakerPoints: { gov: [25,24,25], opp: [24,24,25] } },
          { winnerTeamID: 5, govScore: 78, oppScore: 71, speakerPoints: { gov: [26,26,26], opp: [23,24,24] } },
          { winnerTeamID: 6, govScore: 72, oppScore: 70, speakerPoints: { gov: [24,24,24], opp: [23,23,24] } },
          { winnerTeamID: 7, govScore: 75, oppScore: 69, speakerPoints: { gov: [25,25,25], opp: [22,23,24] } },
          { winnerTeamID: 25, govScore: 73, oppScore: 71, speakerPoints: { gov: [24,24,25], opp: [23,24,24] } },
          { winnerTeamID: 9, govScore: 77, oppScore: 68, speakerPoints: { gov: [26,26,25], opp: [23,23,22] } },
          { winnerTeamID: 23, govScore: 75, oppScore: 72, speakerPoints: { gov: [25,25,25], opp: [24,24,24] } },
          { winnerTeamID: 11, govScore: 74, oppScore: 71, speakerPoints: { gov: [25,24,25], opp: [24,23,24] } },
          { winnerTeamID: 12, govScore: 73, oppScore: 70, speakerPoints: { gov: [24,24,25], opp: [23,23,24] } },
          { winnerTeamID: 13, govScore: 76, oppScore: 69, speakerPoints: { gov: [25,26,25], opp: [23,23,23] } },
          { winnerTeamID: 14, govScore: 71, oppScore: 70, speakerPoints: { gov: [24,24,23], opp: [23,23,24] } },
          { winnerTeamID: 15, govScore: 77, oppScore: 72, speakerPoints: { gov: [26,26,25], opp: [24,24,24] } },
          { winnerTeamID: 16, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [24,23,24] } },
          { winnerTeamID: 17, govScore: 74, oppScore: 70, speakerPoints: { gov: [25,25,24], opp: [23,23,24] } },
          { winnerTeamID: 18, govScore: 73, oppScore: 72, speakerPoints: { gov: [24,25,24], opp: [24,24,24] } },
          { winnerTeamID: 19, govScore: 75, oppScore: 68, speakerPoints: { gov: [25,25,25], opp: [22,23,23] } },
          { winnerTeamID: 20, govScore: 70, oppScore: 69, speakerPoints: { gov: [24,23,23], opp: [23,23,23] } },
        ].map((r, i) => ({ roomID: i + 1, ...r })),
      ],
    },

    // Prelim Round 2 - re-pair (example mixes)
    {
      roundID: 2,
      name: 'Prelim 2',
      pairings: [
        // custom pairings to simulate different opponents
        { roomID: 1, govTeamID: 1, oppTeamID: 20, adjudicators: [1] },
        { roomID: 2, govTeamID: 2, oppTeamID: 19, adjudicators: [2] },
        { roomID: 3, govTeamID: 3, oppTeamID: 18, adjudicators: [3] },
        { roomID: 4, govTeamID: 4, oppTeamID: 17, adjudicators: [4] },
        { roomID: 5, govTeamID: 5, oppTeamID: 16, adjudicators: [5] },
        { roomID: 6, govTeamID: 6, oppTeamID: 15, adjudicators: [6] },
        { roomID: 7, govTeamID: 7, oppTeamID: 14, adjudicators: [7] },
        { roomID: 8, govTeamID: 8, oppTeamID: 13, adjudicators: [8] },
        { roomID: 9, govTeamID: 9, oppTeamID: 12, adjudicators: [9] },
        { roomID: 10, govTeamID: 10, oppTeamID: 11, adjudicators: [10] },
        { roomID: 11, govTeamID: 21, oppTeamID: 40, adjudicators: [1] },
        { roomID: 12, govTeamID: 22, oppTeamID: 39, adjudicators: [2] },
        { roomID: 13, govTeamID: 23, oppTeamID: 38, adjudicators: [3] },
        { roomID: 14, govTeamID: 24, oppTeamID: 37, adjudicators: [4] },
        { roomID: 15, govTeamID: 25, oppTeamID: 36, adjudicators: [5] },
        { roomID: 16, govTeamID: 26, oppTeamID: 35, adjudicators: [6] },
        { roomID: 17, govTeamID: 27, oppTeamID: 34, adjudicators: [7] },
        { roomID: 18, govTeamID: 28, oppTeamID: 33, adjudicators: [8] },
        { roomID: 19, govTeamID: 29, oppTeamID: 32, adjudicators: [9] },
        { roomID: 20, govTeamID: 30, oppTeamID: 31, adjudicators: [10] },
      ],
      results: [
        { roomID: 1, winnerTeamID: 1, govScore: 78, oppScore: 73, speakerPoints: { gov: [26,26,26], opp: [24,24,25] } },
        { roomID: 2, winnerTeamID: 19, govScore: 76, oppScore: 75, speakerPoints: { gov: [25,25,26], opp: [26,25,24] } },
        { roomID: 3, winnerTeamID: 3, govScore: 77, oppScore: 72, speakerPoints: { gov: [26,26,25], opp: [24,24,24] } },
        { roomID: 4, winnerTeamID: 4, govScore: 75, oppScore: 71, speakerPoints: { gov: [25,25,25], opp: [23,24,24] } },
        { roomID: 5, winnerTeamID: 5, govScore: 79, oppScore: 71, speakerPoints: { gov: [27,26,26], opp: [23,24,24] } },
        { roomID: 6, winnerTeamID: 6, govScore: 73, oppScore: 72, speakerPoints: { gov: [24,24,25], opp: [24,24,24] } },
        { roomID: 7, winnerTeamID: 7, govScore: 74, oppScore: 70, speakerPoints: { gov: [25,24,25], opp: [23,23,24] } },
        { roomID: 8, winnerTeamID: 8, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [23,24,24] } },
        { roomID: 9, winnerTeamID: 12, govScore: 75, oppScore: 73, speakerPoints: { gov: [25,25,25], opp: [24,24,25] } },
        { roomID: 10, winnerTeamID: 11, govScore: 74, oppScore: 70, speakerPoints: { gov: [25,24,25], opp: [23,23,24] } },
        { roomID: 11, winnerTeamID: 21, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [24,23,24] } },
        { roomID: 12, winnerTeamID: 22, govScore: 73, oppScore: 72, speakerPoints: { gov: [24,24,25], opp: [24,24,24] } },
        { roomID: 13, winnerTeamID: 23, govScore: 76, oppScore: 69, speakerPoints: { gov: [26,25,25], opp: [23,23,23] } },
        { roomID: 14, winnerTeamID: 24, govScore: 71, oppScore: 69, speakerPoints: { gov: [24,24,23], opp: [23,23,23] } },
        { roomID: 15, winnerTeamID: 25, govScore: 75, oppScore: 72, speakerPoints: { gov: [25,25,25], opp: [24,24,24] } },
        { roomID: 16, winnerTeamID: 26, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [24,23,24] } },
        { roomID: 17, winnerTeamID: 27, govScore: 73, oppScore: 70, speakerPoints: { gov: [24,25,24], opp: [23,23,24] } },
        { roomID: 18, winnerTeamID: 28, govScore: 74, oppScore: 72, speakerPoints: { gov: [25,24,25], opp: [24,24,24] } },
        { roomID: 19, winnerTeamID: 29, govScore: 76, oppScore: 71, speakerPoints: { gov: [26,25,25], opp: [23,24,24] } },
        { roomID: 20, winnerTeamID: 30, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [24,23,24] } },
      ],
    },

    // Prelim Round 3
    {
      roundID: 3,
      name: 'Prelim 3',
      pairings: [
        // another distribution
        { roomID: 1, govTeamID: 1, oppTeamID: 19, adjudicators: [1] },
        { roomID: 2, govTeamID: 2, oppTeamID: 18, adjudicators: [2] },
        { roomID: 3, govTeamID: 3, oppTeamID: 17, adjudicators: [3] },
        { roomID: 4, govTeamID: 4, oppTeamID: 16, adjudicators: [4] },
        { roomID: 5, govTeamID: 5, oppTeamID: 15, adjudicators: [5] },
        { roomID: 6, govTeamID: 6, oppTeamID: 14, adjudicators: [6] },
        { roomID: 7, govTeamID: 7, oppTeamID: 13, adjudicators: [7] },
        { roomID: 8, govTeamID: 8, oppTeamID: 12, adjudicators: [8] },
        { roomID: 9, govTeamID: 9, oppTeamID: 11, adjudicators: [9] },
        { roomID: 10, govTeamID: 10, oppTeamID: 20, adjudicators: [10] },
        { roomID: 11, govTeamID: 21, oppTeamID: 38, adjudicators: [1] },
        { roomID: 12, govTeamID: 22, oppTeamID: 37, adjudicators: [2] },
        { roomID: 13, govTeamID: 23, oppTeamID: 36, adjudicators: [3] },
        { roomID: 14, govTeamID: 24, oppTeamID: 35, adjudicators: [4] },
        { roomID: 15, govTeamID: 25, oppTeamID: 34, adjudicators: [5] },
        { roomID: 16, govTeamID: 26, oppTeamID: 33, adjudicators: [6] },
        { roomID: 17, govTeamID: 27, oppTeamID: 32, adjudicators: [7] },
        { roomID: 18, govTeamID: 28, oppTeamID: 31, adjudicators: [8] },
        { roomID: 19, govTeamID: 29, oppTeamID: 30, adjudicators: [9] },
        { roomID: 20, govTeamID: 39, oppTeamID: 40, adjudicators: [10] },
      ],
      results: [
        { roomID: 1, winnerTeamID: 1, govScore: 80, oppScore: 73, speakerPoints: { gov: [27,27,26], opp: [24,24,25] } },
        { roomID: 2, winnerTeamID: 2, govScore: 75, oppScore: 72, speakerPoints: { gov: [25,25,25], opp: [24,24,24] } },
        { roomID: 3, winnerTeamID: 3, govScore: 78, oppScore: 71, speakerPoints: { gov: [26,26,26], opp: [24,24,23] } },
        { roomID: 4, winnerTeamID: 16, govScore: 76, oppScore: 75, speakerPoints: { gov: [26,25,25], opp: [25,25,25] } },
        { roomID: 5, winnerTeamID: 5, govScore: 79, oppScore: 73, speakerPoints: { gov: [27,26,26], opp: [24,24,25] } },
        { roomID: 6, winnerTeamID: 14, govScore: 74, oppScore: 72, speakerPoints: { gov: [25,24,25], opp: [24,24,24] } },
        { roomID: 7, winnerTeamID: 7, govScore: 75, oppScore: 71, speakerPoints: { gov: [25,25,25], opp: [23,24,24] } },
        { roomID: 8, winnerTeamID: 8, govScore: 73, oppScore: 70, speakerPoints: { gov: [24,24,25], opp: [23,23,24] } },
        { roomID: 9, winnerTeamID: 9, govScore: 76, oppScore: 74, speakerPoints: { gov: [25,26,25], opp: [25,24,25] } },
        { roomID: 10, winnerTeamID: 30, govScore: 72, oppScore: 70, speakerPoints: { gov: [24,24,24], opp: [23,23,24] } },
        { roomID: 11, winnerTeamID: 21, govScore: 74, oppScore: 72, speakerPoints: { gov: [24,25,25], opp: [24,24,24] } },
        { roomID: 12, winnerTeamID: 22, govScore: 73, oppScore: 72, speakerPoints: { gov: [24,24,25], opp: [24,24,24] } },
        { roomID: 13, winnerTeamID: 23, govScore: 76, oppScore: 70, speakerPoints: { gov: [26,25,25], opp: [23,23,24] } },
        { roomID: 14, winnerTeamID: 24, govScore: 71, oppScore: 69, speakerPoints: { gov: [24,24,23], opp: [23,23,23] } },
        { roomID: 15, winnerTeamID: 25, govScore: 75, oppScore: 73, speakerPoints: { gov: [25,25,25], opp: [24,24,25] } },
        { roomID: 16, winnerTeamID: 26, govScore: 72, oppScore: 71, speakerPoints: { gov: [24,24,24], opp: [24,23,24] } },
        { roomID: 17, winnerTeamID: 27, govScore: 73, oppScore: 70, speakerPoints: { gov: [24,25,24], opp: [23,23,24] } },
        { roomID: 18, winnerTeamID: 28, govScore: 74, oppScore: 72, speakerPoints: { gov: [25,24,25], opp: [24,24,24] } },
        { roomID: 19, winnerTeamID: 29, govScore: 76, oppScore: 71, speakerPoints: { gov: [26,25,25], opp: [23,24,24] } },
        { roomID: 20, winnerTeamID: 39, govScore: 73, oppScore: 71, speakerPoints: { gov: [24,24,25], opp: [24,23,24] } },
      ],
    },

    // Semifinals - top 4 teams from prelims (determined by wins + speaker points)
    {
      roundID: 4,
      name: 'Semifinal',
      pairings: [
        { roomID: 1, govTeamID: 1, oppTeamID: 3, adjudicators: [1,2,3] },
        { roomID: 2, govTeamID: 2, oppTeamID: 5, adjudicators: [4,5,6] },
      ],
      results: [
        { roomID: 1, winnerTeamID: 1, govScore: 81, oppScore: 75, speakerPoints: { gov: [28,27,26], opp: [25,25,25] } },
        { roomID: 2, winnerTeamID: 3, govScore: 78, oppScore: 77, speakerPoints: { gov: [26,26,26], opp: [26,25,26] } },
      ],
    },

    // Final
    {
      roundID: 5,
      name: 'Final',
      pairings: [
        { roomID: 1, govTeamID: 1, oppTeamID: 3, adjudicators: [1,2,3,4,5] },
      ],
      results: [
        { roomID: 1, winnerTeamID: 1, govScore: 82, oppScore: 78, speakerPoints: { gov: [28,27,27], opp: [26,26,26] } },
      ],
    },
  ],

  individualStandings: [
    // per-speaker preliminary totals (to be computed from prelim rounds)
    // format: { participantID, name, teamID, prelimTotalSpeakerPoints, prelimRounds: number }
    { participantID: 1, name: 'Alex P.', teamID: 1, prelimTotalSpeakerPoints: 0, prelimRounds: 3 },
    { participantID: 2, name: 'Bea Q.', teamID: 1, prelimTotalSpeakerPoints: 0, prelimRounds: 3 },
    { participantID: 3, name: 'Carl R.', teamID: 1, prelimTotalSpeakerPoints: 0, prelimRounds: 3 },
    // add remaining participants' individual standings as needed
  ],

  standings: [
    // summarised after prelims + elimination
    { rank: 1, teamID: 1, name: 'Greenwood A', wins: 3, speakerPointsTotal: 493, placement: 'Champion' },
    { rank: 2, teamID: 3, name: 'Hilltop A', wins: 3, speakerPointsTotal: 466, placement: 'Runner-up' },
    { rank: 3, teamID: 2, name: 'Lakeside A', wins: 3, speakerPointsTotal: 451, placement: 'Semifinalist' },
    { rank: 4, teamID: 5, name: 'Maple A', wins: 3, speakerPointsTotal: 457, placement: 'Semifinalist' },
    // next teams by prelim results
    { rank: 5, teamID: 9, name: 'Riverside B', wins: 2, speakerPointsTotal: 458 },
    { rank: 6, teamID: 12, name: 'Lakeside C', wins: 2, speakerPointsTotal: 444 },
    { rank: 7, teamID: 23, name: 'Hilltop E', wins: 2, speakerPointsTotal: 446 },
    { rank: 8, teamID: 25, name: 'Maple E', wins: 2, speakerPointsTotal: 449 },
    // mid table
    { rank: 9, teamID: 29, name: 'Riverside F', wins: 2, speakerPointsTotal: 451 },
    { rank: 10, teamID: 30, name: 'Maple F', wins: 2, speakerPointsTotal: 446 },
    // bottom half (sample)
    { rank: 38, teamID: 38, name: 'Hilltop H', wins: 0, speakerPointsTotal: 360 },
    { rank: 39, teamID: 39, name: 'Swing Team 1', wins: 1, speakerPointsTotal: 373, swing: true },
    { rank: 40, teamID: 40, name: 'Swing Team 2', wins: 0, speakerPointsTotal: 362, swing: true },
  ],
};
